import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Landing Page Tema Restaurante",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className="bg-bg">{children}</main>;
}
